### ISSUE TITLE
use in browser, getting an error

### ISSUE THREAD

**Issue by resession** [draeder/zerok#2]
getting this error

`Uncaught ReferenceError: Buffer is not defined`

from one of the dependency `paillier-js`

**Comment by draeder** [comment]
Please use the CDN: `<script src="https://cdn.jsdelivr.net/gh/draeder/zerok@master/zerok.bundle.js"></script>` 

Looks like I forgot to document it in the readme...

**Comment by draeder** [comment]
Hmm... seems like the bundler didn't package it correctly. Should be fixed. 

Updated link once jsdelivr picks up the changes: 
```html
<script src="https://cdn.jsdelivr.net/gh/draeder/zerok@master/dist/zerok.dist.js"></script>
```

In the meantime, you can get the file from the `dist` folder in this repo. Also updated the readme.
